In [2]:
import numpy as np
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import numpy as geek 
  
# input array 
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays along axis 0 
out_arr1 = geek.stack((in_arr1, in_arr2), axis = 0) 
print ("Output stacked array along axis 0:\n ", out_arr1) 
  
# Stacking the two arrays along axis 1 
out_arr2 = geek.stack((in_arr1, in_arr2), axis = 1) 
print ("Output stacked array along axis 1:\n ", out_arr2) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output stacked array along axis 0:
  [[1 2 3]
 [4 5 6]]
Output stacked array along axis 1:
  [[1 4]
 [2 5]
 [3 6]]


In [6]:
import os
data = np.loadtxt(os.path.join('Data', 'part1data1.txt'), delimiter=',')
X, y = data[:, 0], data[:, 1]

m = y.size  # number of training examples
X = np.stack([np.ones(m), X], axis=1)


In [10]:
def computeCost(X, y, theta):

    J = 0
    S = 0
    for i in range (m):
        S += (theta[0] + theta[1] *X[i][1] - y[i])**2
    J = 1/(2*m)*S
    return J


In [11]:
J = computeCost(X, y, theta=np.array([0.0, 0.0]))
print('With theta = [0, 0] \nCost computed = %.2f' % J)
print('Expected cost value (approximately) 32.07\n')

# further testing of the cost function
J = computeCost(X, y, theta=np.array([-1, 2]))
print('With theta = [-1, 2]\nCost computed = %.2f' % J)
print('Expected cost value (approximately) 54.24')

With theta = [0, 0] 
Cost computed = 32.07
Expected cost value (approximately) 32.07

With theta = [-1, 2]
Cost computed = 54.24
Expected cost value (approximately) 54.24


In [22]:
XX = np.array([[1,0], [1,1], [1,2], [1,3], [1,4]])
yy = np.array([1,2,3,4,5])
theta = np.array([1.5, 3])

m = yy.shape[0]
alpha = 0.01

In [21]:
#method1
s0 = 0
s1 = 0
for i in range(m):
    s0 += theta[0] + theta[1]*XX[i][1] - yy[i]
    s1 += (theta[0] + theta[1]*XX[i][1] - yy[i])*XX[i][1]
print(s0, s1)
    

22.5 65.0


In [23]:
#method2
((X.dot(theta.T) - y).T).dot(X)

array([ 1953.6057   , 18538.8998359])

In [46]:
a = np.array([[1,2,],[1,3],[1,4]])
a.shape

(3, 2)

In [55]:
b = a[:,[1]]
b

array([[2],
       [3],
       [4]])

In [58]:
b.T

array([[2, 3, 4]])

In [66]:
a = (X.dot(theta.T) - y)
a.shape
b = (X[:,0])
b.shape
a*b

array([ 2.2383 ,  8.9529 , 13.3938 , 10.6556 , 12.2561 , 14.7627 ,
       19.5809 , 15.2343 , 14.3599 , 12.8472 , 15.3799 , 28.487  ,
       15.5469 , 19.4994 , 17.70592, 14.1253 , 15.2914 , 16.32953,
       17.137  , 17.3231 , 16.9287 , 40.543  , 13.7073 , 15.2908 ,
       15.1122 , 35.697  , 26.483  , 27.3243 , 26.336  , 43.962  ,
       18.4772 , 15.2716 , 17.1106 , 17.3259 , 19.5907 , 20.7379 ,
       21.6713 , 14.9261 , 29.891  , 15.0628 , 17.16413, 18.236  ,
       31.2386 , 16.3805 , 18.2423 , 21.733  , 11.5769 , 17.0602 ,
       28.5957 , 17.1069 , 17.3702 , 15.5835 , 19.4832 , 19.3112 ,
       19.0751 , 21.9978 , 17.847  , 13.8149 , 25.4682 , 24.4467 ,
       22.8068 , 17.78069, 47.408  , 34.17   , 41.323  , 18.2694 ,
       20.6411 , 24.4326 , 16.9809 , 41.531  , 25.2281 , 19.4776 ,
       18.2402 , 19.8366 , 19.2614 , 20.84692, 20.2313 , 10.9081 ,
       25.5694 , 14.7655 , 18.20807, 16.86099, 19.88849, 23.2626 ,
       15.7041 , 22.8101 , 22.2425 , 18.57905, 17.9092 , 13.85

In [25]:
import numpy as np
a = np.array([[1,2,3,8],[3,4,5,8]])
np.std(a, axis=0)

array([1., 1., 1., 0.])

In [26]:
a = np.array([3, 4,5])
np.std(a)

0.816496580927726

In [29]:
import math
math.sqrt(2/3)

0.816496580927726

In [40]:
import copy
X = np.array([[1.0,2.0,3.0,3.0],[4.0,5.0,6.0,4.0],[7.0,8.0,9.0,2.0]])
X_norm = X.copy()
mu = np.zeros(X.shape[1])
sigm = np.zeros(X.shape[1])
for i in range (X.shape[1]):
    mu[i] = np.mean(X[:,i])
    sigm[i] = np.std(X[:,i])
    X_norm[:,i] = (X[:,i] - mu[i]) / sigm[i]

print(X_norm)

[[-1.22474487 -1.22474487 -1.22474487  0.        ]
 [ 0.          0.          0.          1.22474487]
 [ 1.22474487  1.22474487  1.22474487 -1.22474487]]


In [53]:
a = np.zeros(3)
a.shape[0]

3

In [55]:
X = np.array([[1,1,2],[1,3,4],[1,5,6],[1,7,8]])
X.shape
# X.dot(a)
a.dot(X.T)

array([0., 0., 0., 0.])

In [69]:
a = []
a.append([1,2])
a

[[1, 2]]

In [67]:
list_alpha = np.arange(0.001,0.2,0.001)
print(list_alpha.shape)
list_J_history = np.zeros(list_alpha.shape[0])
print(list_J_history.shape)


(199,)
(199,)


In [71]:
a = [1,2,4,5,0]
a.index(min(a))

4

In [72]:
np.exp(1)

2.718281828459045

In [73]:
math.exp(1)

2.718281828459045

In [77]:
a = np.array(0)
a.shape

()

In [79]:
a = np.array([1,2,3])
1 -a

array([ 0, -1, -2])

In [82]:
X = np.array([[1,2,3],[1,4,5],[1,6,7],[1,7,8]])
y = np.array([1,0,1,0])
X.shape

(4, 3)

In [83]:
np.zeros(X.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))
x

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


array([[ 0, 10, 20],
       [20, 30, 40]])

In [86]:
x[x>10] = 0


In [87]:
x

array([[ 0, 10,  0],
       [ 0,  0,  0]])

In [90]:
x[ np.where( x > 3 ) ] = 1

In [92]:
x = np.array([[0, 10, 20], [20, 30, 40]])
x[ np.where( x > 0 ) ] = 1
x[ np.where( x <= 0 ) ] = 0

In [93]:
x

array([[0, 1, 1],
       [1, 1, 1]])

In [94]:
a = np.array([1,2,3])
a**2

array([1, 4, 9])